const products=[
{id:1,name:'Portable Bluetooth Speaker',category:'AUDIO',subtitle:'Wireless audio speaker',price:129.99,oldPrice:null,rating:3.5,reviews:32,img:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80',imgs:['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&w=900&q=80'],desc:'Take your music anywhere with this powerful portable speaker. Delivers rich, immersive sound with deep bass. Waterproof design perfect for outdoor adventures and pool parties.',features:['Output Power: 20W','Battery Life: 15 hours','Water Rating: IPX7']},
{id:2,name:'Premium Wireless Headphones',category:'AUDIO',subtitle:'Noise-cancelling headphones',price:299.99,rating:5,reviews:15,img:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',imgs:['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80'],desc:'Premium wireless headphones with active noise cancellation, comfortable ear cups and crystal-clear sound for music, calls and travel.',features:['Active noise cancellation','Battery Life: 30 hours','Bluetooth 5.3']},
{id:3,name:'Professional DSLR Camera',category:'PHOTOGRAPHY',subtitle:'Full-frame camera kit',price:2499.99,rating:5,reviews:64,img:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80',imgs:['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1480365501497-199581be0e66?auto=format&fit=crop&w=900&q=80'],desc:'Professional DSLR camera for advanced photography, video recording and creative work.',features:['Full-frame sensor','4K video recording','Weather-sealed body']},
{id:4,name:'Professional Laptop Pro',category:'COMPUTERS',subtitle:'Performance laptop',price:1899.99,rating:4.5,reviews:45,img:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',imgs:['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=900&q=80'],desc:'Powerful laptop for work, design, study and multitasking with premium build quality.',features:['16GB RAM','1TB SSD','High-resolution display']},
{id:5,name:'Smart Fitness Watch Ultra',category:'WEARABLES',subtitle:'Fitness smartwatch',price:449.99,rating:4,reviews:41,img:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',imgs:['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=900&q=80'],desc:'Advanced fitness watch with activity tracking, heart-rate monitoring and bright always-on display.',features:['GPS tracking','Heart-rate monitor','Water resistant']},
{id:6,name:'Ultra-Thin Tablet Pro',category:'TABLETS',subtitle:'Portable tablet',price:799.99,rating:4.5,reviews:21,img:'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80',imgs:['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=900&q=80'],desc:'Ultra-thin tablet with a vivid display, long battery life and smooth everyday performance.',features:['12.9 inch display','Fast charging','Stylus support']}
];
let state={sort:'az',ratings:[],max:3000,min:0,slide:0,qty:1,promo:'',msg:''};
const CART='techstore_cart_v1';
const getCart=()=>JSON.parse(localStorage.getItem(CART)||'[]');
const setCart=c=>{localStorage.setItem(CART,JSON.stringify(c));render();};
const money=n=>'$'+n.toFixed(2);
const count=()=>getCart().reduce((s,i)=>s+i.qty,0);
function add(id,qty=1){const cart=getCart();const item=cart.find(x=>x.id===id);if(item)item.qty+=qty;else cart.push({id,qty});setCart(cart)}
function change(id,d){let cart=getCart().map(x=>x.id===id?{...x,qty:Math.max(1,x.qty+d)}:x);setCart(cart)}
function removeItem(id){setCart(getCart().filter(x=>x.id!==id))}
function stars(r){
  let s='';
  for(let i=1;i<=5;i++){
    const cls=i<=Math.floor(r)?'full':(r>=i-.5?'half':'empty');
    s+=`<span class="star ${cls}">★</span>`;
  }
  return `<span class="stars" aria-label="Rating ${r} out of 5">${s}</span>`;
}
function header(){return `<header class="top"><a class="brand" href="#/"><span>T</span><b>TechStore</b></a><nav><a href="#/">Products</a><a href="#/">Categories</a><a href="#/">Deals</a><a href="#/">About</a></nav><div class="icons"><button aria-label="Search" class="iconBtn"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"></circle><path d="M20 20l-3.5-3.5"></path></svg></button><a class="cartIcon" href="#/cart" aria-label="Cart"><svg viewBox="0 0 24 24"><path d="M6 6h15l-1.6 8.2a2 2 0 0 1-2 1.6H9.1a2 2 0 0 1-2-1.7L5.2 3H2"></path><circle cx="9" cy="20" r="1.5"></circle><circle cx="18" cy="20" r="1.5"></circle></svg>${count()?`<i>${count()}</i>`:''}</a></div></header>`}
function footer(){return `<footer><div class="footgrid"><div><div class="brand footbrand"><span>T</span><b>TechStore</b></div><p>Your trusted destination for premium electronics and tech accessories. Quality products, competitive prices, exceptional service.</p><div class="social"><span>f</span><span>𝕏</span><span>◎</span><span>▶</span></div></div><div><h3>Quick Links</h3><a>Shop All Products</a><a>Special Deals</a><a>About Us</a><a>Contact Support</a></div><div><h3>Customer Service</h3><a>Shipping Information</a><a>Returns & Exchanges</a><a>FAQ</a><a>Track Order</a><p>Customer Support:<br><b>1-800-TECH-SHOP</b><br>support@techstore.com</p></div><div><h3>Newsletter</h3><p>Subscribe to get special offers, free giveaways, and updates.</p><input placeholder="Enter your email"><button>Subscribe</button></div></div><div class="copy">© 2026 TechStore. All rights reserved.<br><span>Privacy Policy &nbsp;&nbsp; Terms of Service &nbsp;&nbsp; Cookie Policy</span></div></footer>`}
function catalog(){let list=[...products].filter(p=>p.price>=state.min&&p.price<=state.max&&(state.ratings.length===0||state.ratings.some(r=>p.rating>=r)));list.sort((a,b)=>state.sort==='az'?a.name.localeCompare(b.name):state.sort==='za'?b.name.localeCompare(a.name):state.sort==='cheap'?a.price-b.price:b.price-a.price);return `<main class="wrap"><section class="hero"><h1>Premium Electronics</h1><p>Discover our curated collection of high-quality tech products</p></section><div class="bar"><span>${list.length} products</span><label>Sort by:<select onchange="state.sort=this.value;render()"><option value="az" ${state.sort==='az'?'selected':''}>Name (A-Z)</option><option value="za" ${state.sort==='za'?'selected':''}>Name (Z-A)</option><option value="cheap" ${state.sort==='cheap'?'selected':''}>Price Low to High</option><option value="exp" ${state.sort==='exp'?'selected':''}>Price High to Low</option></select></label></div><div class="layout"><aside class="filters"><h2>☷ Filters</h2><h3>Rating</h3>${[5,4,3].map(r=>`<label class="check"><input type="checkbox" ${state.ratings.includes(r)?'checked':''} onchange="toggleRating(${r})"><span></span>${r}+ Stars</label>`).join('')}<h3>Price Range</h3><input type="range" min="0" max="3000" value="${state.max}" oninput="state.max=+this.value;render()"><div class="range"><span>$0</span><span>$${state.max}</span></div><button class="ghost" onclick="state.ratings=[];state.max=3000;render()">Clear All Filters</button></aside><section class="grid">${list.map(card).join('')}</section></div></main>`}
function toggleRating(r){state.ratings=state.ratings.includes(r)?state.ratings.filter(x=>x!==r):[...state.ratings,r];render()}
function card(p){return `<article class="card"><a href="#/product/${p.id}"><img src="${p.img}" alt="${p.name}"></a><div class="cardbody"><a class="title" href="#/product/${p.id}">${p.name}</a><div>${stars(p.rating)} <span class="rate">(${p.rating})</span></div><div class="priceRow"><b>${money(p.price)}</b><small>${p.category}</small></div><button class="add" onclick="add(${p.id})">Add to Cart</button></div></article>`}
function productPage(id){const p=products.find(x=>x.id==id)||products[0];return `<main class="wrap product"><div class="crumb">Products › ${p.category[0]+p.category.slice(1).toLowerCase()} › ${p.name}</div><section class="productGrid"><div><div class="big"><button onclick="state.slide=(state.slide+2)%3;render()">‹</button><img src="${p.imgs[state.slide]}"><button onclick="state.slide=(state.slide+1)%3;render()">›</button></div><div class="thumbs">${p.imgs.map((im,i)=>`<img class="${i===state.slide?'active':''}" onclick="state.slide=${i};render()" src="${im}">`).join('')}</div><h3>Related Products</h3><div class="related">${products.filter(x=>x.id!==p.id).slice(0,1).map(card).join('')}</div></div><div class="info"><h1>${p.name}</h1><div>${stars(p.rating)} <span class="rate">${p.rating} (${p.reviews})</span></div><p class="muted">Based on ${p.reviews} reviews</p><h2>${money(p.price)} <span>Free shipping</span></h2><div class="features"><b>Key Highlights:</b><ul>${p.features.map(f=>`<li>${f}</li>`).join('')}</ul></div><h3>Description</h3><p>${p.desc}</p><label class="qtylbl">Quantity</label><div class="qty"><button onclick="state.qty=Math.max(1,state.qty-1);render()">-</button><span>${state.qty}</span><button onclick="state.qty++;render()">+</button></div><button class="primary" onclick="add(${p.id},state.qty);state.qty=1"><span class="cartMini">🛒</span> Add to Cart</button><details><summary>Technical Specifications</summary><p>High quality materials, warranty 12 months, original packaging included.</p></details></div></section></main>`}
function cartPage(){const cart=getCart(); if(!cart.length)return `<main class="wrap empty"><h2>Your Cart is Empty</h2><p>Add some amazing products to get started!</p><a class="primary link" href="#/">Continue Shopping</a></main>`; const rows=cart.map(i=>({...products.find(p=>p.id===i.id),qty:i.qty})); const sub=rows.reduce((s,i)=>s+i.price*i.qty,0); const tax=sub*.08; const discount=state.promo.toUpperCase()==='SAVE10'?sub*.1:0; const total=sub+tax-discount; return `<main class="wrap cartPage"><h1>Shopping Cart</h1><div class="cartGrid"><section>${rows.map(i=>`<div class="cartItem"><img src="${i.img}"><div><b>${i.name}</b><p>${i.subtitle}</p><div class="qty"><button onclick="change(${i.id},-1)">-</button><span>${i.qty}</span><button onclick="change(${i.id},1)">+</button></div></div><div class="itemRight"><button onclick="removeItem(${i.id})">⌫</button><b>${money(i.price*i.qty)}</b><small>${money(i.price)} each</small></div></div>`).join('')}</section><aside class="summary"><h3>Order Summary</h3><p><span>Subtotal</span><b>${money(sub)}</b></p><p><span>Tax (8%)</span><b>${money(tax)}</b></p>${discount?`<p class="green"><span>Discount</span><b>-${money(discount)}</b></p>`:''}<hr><p class="total"><span>Total</span><b>${money(total)}</b></p><label>Promo Code</label><div class="promo"><input id="promo" placeholder="Enter code"><button onclick="applyPromo()">Apply</button></div><small>${state.msg||'Try code "SAVE10" for 10% off'}</small><button class="primary">Proceed to Checkout</button><div class="ship"><h4>▣ Shipping Information</h4><p><b>Delivery Address</b><br>123 Tech Street<br>San Francisco, CA 94105</p><p><b>Estimated Delivery</b><br><span class="green">3-5 business days</span><br><span class="green">Free shipping on orders over $50</span></p></div></aside></div></main>`}
function applyPromo(){const v=document.getElementById('promo').value.trim();if(!v){state.msg='Введите промокод';return render()} if(v.toUpperCase()==='SAVE10'){state.promo='SAVE10';state.msg='Promo code applied'}else{state.promo='';state.msg='Неверный промокод'}render()}
function render(){const route=location.hash||'#/';let page=route.startsWith('#/product/')?productPage(route.split('/').pop()):route==='#/cart'?cartPage():catalog();document.getElementById('app').innerHTML=header()+page+footer()}
window.addEventListener('hashchange',()=>{state.slide=0;render()});render();
